<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    use HasFactory;

    // protected $table = 'cities'; // auto-generated by Laravel
    // protected $primaryKey = 'id'; // auto-generated by Laravel
}
