<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    use HasFactory;

    // protected $table = 'projects'; // auto-generated by Laravel
    // protected $primaryKey = 'id'; // auto-generated by Laravel
    // protected $attributes = [
    //     'name' => 'NN' // default value for the column
    // ];
}
